/*
 * This source file was generated by the Gradle 'init' task
 */
package org.aether;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull("app should have a greeting\"", "app should have a greeting");
    }
}
