spring:
  application:
    name: aether

  main:
    banner-mode: "off"

  profiles:
    default: dev

  task:
    execution:
      propagate-context: true

  config:
    import:
      - classpath:config/database.yml
      - classpath:config/security.yml

logging:
    pattern:
      console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] [traceId=%X{traceId:-}] [correlationId=%X{correlationId:-}] [executionId=%X{executionId:-}] [attempt=%X{attempt:-}] %logger{36} - %msg%n"

aether:
  service-name: ${AETHER_SERVICE_NAME:aether}
  max-page-size: ${AETHER_MAX_PAGE_SIZE:100}
  security:
    enabled: ${AETHER_SECURITY_ENABLED:true}
    issuers:
      - name: ${AETHER_SECURITY_ISSUER_NAME:keycloak-local}
        provider: ${AETHER_SECURITY_PROVIDER:KEYCLOAK}
        issuer-uri: ${AETHER_SECURITY_ISSUER_URI:http://localhost:8180/realms/aether}
        audience: ${AETHER_SECURITY_AUDIENCE:aether-api}
        principal-claim: ${AETHER_SECURITY_PRINCIPAL_CLAIM:sub}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
